### ISSUE TITLE
Cloud of microdungeons are still there on ocean worlds

### ISSUE THREAD

**Issue by AllanDoodes** [dsp2003/clef#8]
Sorry if I shoud have re-opened the last issue, but couldn't see an obvious way of doing so.

I have seen the edge of what looks like the microdungeon cloud inside a tropical ocean planet. I was roughly 500 blocks below the seabed, and the planet was size 16000.

This is with the version of CLeF current on GitHub today - 14/1/16.

I assume you put the test code in more places than you recalled when making the lastest changes.

Sorry to harp on about this.

**Comment by dsp2003** [comment]
If these were the only thing that occupied the particular layer, it means there were no other dungeons in the list in the first place.

Anyway, just committed the "fix". This will remove them from spawning lists until I'll re-add them as custom dungeons, which spawning rates are more sane.

**Comment by AllanDoodes** [comment]
Thanks again.

**Comment by dsp2003** [comment]
You're welcome. :)
